language: c

python:
    - "2.7"

os:
    - linux
    - osx

dist: trusty

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python glib argp-standalone; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq;  fi
      # needed to install scipy
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libblas-dev liblapack-dev gfortran; fi
      # fastFM-core dependencies
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y python-dev libglib2.0-dev libatlas-base-dev libgsl0-dev; fi

install:
    - git submodule update --init --recursive
    - pip install --user -r requirements.txt
    - pip install --user nose
    - make
    - pip install --user .

script:
    # travis issue for osx, some libraries are build for x86_64 and others for i386.
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then nosetests; fi
