language: python

python:
    - "2.7"

os:
    - linux
    - osx

dist: trusty

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python glib argp-standalone; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq;  fi
      # needed to install scipy
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libblas-dev liblapack-dev gfortran; fi
      # fastFM-core dependencies
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y python-dev libglib2.0-dev libatlas-base-dev libgsl0-dev; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy pandas scipy scikit-learn nose
    - source activate test-environment

install:
    - git submodule update --init --recursive
    - make
    - pip install .

script:
    # travis issue for osx, some libraries are build for x86_64 and others for i386.
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then nosetests; fi
