- name: build and install
  hosts: dev
  become: true
  gather_facts: false
  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:

  tasks:
    - name: set facts
      set_fact:
        fastfm_dir: ~/fastFM/

    - name: set facts
      set_fact:
        musl_build: true
        core2_dir: "{{ fastfm_dir }}/fastFM-core2"
        build_type: Release

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - build-essential
        - cmake
        - make
        - git
        - python
        - python-pip
        - htop

- name: setup fastFM
  hosts: dev
  environment:
    LC_ALL: C # needed to fix pip
  tasks:
    - name: clone fastFM
      git:
         accept_hostkey: yes
         repo: git@github.com:ibayer/fastFM.git
         dest: "{{ fastfm_dir }}"
         version: cython-wrapper # checkout branch
         force: yes # override any local changes
         recursive: yes

    - name: build fastFM-core
      make:
          chdir: "{{ fastfm_dir }}/fastFM-core"

    - name: pip install
      pip:
         requirements: "{{ fastfm_dir }}/requirements.txt"

- include: ../fastFM-core2/playbooks/core_build.yml

- name: build fastFM
  hosts: dev
  environment:
    LC_ALL: C # needed to fix pip
    HUNTER_LIBRARY_DIR: "{{ hunter_install_dir }}/Install/lib/"
  tasks:
    - debug:
        msg: "hunter_install_dir: {{ hunter_install_dir }}"

    - name: build fastFM wheel
      command: python setup.py bdist_wheel
      args:
        chdir: "{{ fastfm_dir }}"

    - name: copy weehl to local
      synchronize:  src="{{ fastfm_dir }}/dist" dest=/tmp/ mode=pull
